// Dummy data for Guest Mode demonstration

import { Timestamp } from "firebase/firestore";
import { Lead, Message, Task, Automation, DashboardStats } from "./types";
import { subDays, subHours, addDays, addHours } from "date-fns";

// Helper to create Timestamp from Date
const toTimestamp = (date: Date) => Timestamp.fromDate(date);

export const DUMMY_LEADS: Lead[] = [
  {
    id: "lead-1",
    user_id: "guest-user",
    assigned_to: "guest-user",
    name: "Rahul Sharma",
    phone: "+919876543001",
    email: "rahul.sharma@email.com",
    source: "website",
    budget: 7500000,
    location: "Whitefield, Bangalore",
    property_type: "flat",
    status: "visit_scheduled",
    notes: "Looking for 3BHK, interested in gated community",
    tags: ["premium"],
    lead_score: 85,
    lead_priority: "HOT",
    last_interaction_at: toTimestamp(subHours(new Date(), 2)),
    visit_scheduled_at: toTimestamp(addDays(new Date(), 1)),
    message_count: 8,
    created_at: toTimestamp(subDays(new Date(), 5)),
    updated_at: toTimestamp(subHours(new Date(), 2)),
  },
  {
    id: "lead-2",
    user_id: "guest-user",
    assigned_to: "guest-user",
    name: "Priya Menon",
    phone: "+919876543002",
    email: "priya.m@email.com",
    source: "whatsapp",
    budget: 4500000,
    location: "Electronic City",
    property_type: "flat",
    status: "negotiation",
    notes: "First-time buyer, needs loan assistance",
    lead_score: 72,
    lead_priority: "WARM",
    last_interaction_at: toTimestamp(subHours(new Date(), 6)),
    message_count: 5,
    created_at: toTimestamp(subDays(new Date(), 8)),
    updated_at: toTimestamp(subHours(new Date(), 6)),
  },
  {
    id: "lead-3",
    user_id: "guest-user",
    assigned_to: "guest-user",
    name: "Amit Patel",
    phone: "+919876543003",
    email: "amit.patel@email.com",
    source: "portal",
    budget: 15000000,
    location: "Indiranagar",
    property_type: "villa",
    status: "new",
    notes: "Investment purpose, looking for ready-to-move",
    lead_score: 65,
    lead_priority: "WARM",
    last_interaction_at: toTimestamp(subDays(new Date(), 1)),
    message_count: 2,
    created_at: toTimestamp(subDays(new Date(), 2)),
    updated_at: toTimestamp(subDays(new Date(), 1)),
  },
  {
    id: "lead-4",
    user_id: "guest-user",
    assigned_to: "guest-user",
    name: "Sunita Reddy",
    phone: "+919876543004",
    source: "facebook",
    budget: 3500000,
    location: "Marathahalli",
    property_type: "flat",
    status: "contacted",
    lead_score: 55,
    lead_priority: "WARM",
    last_interaction_at: toTimestamp(subDays(new Date(), 2)),
    message_count: 3,
    created_at: toTimestamp(subDays(new Date(), 10)),
    updated_at: toTimestamp(subDays(new Date(), 2)),
  },
  {
    id: "lead-5",
    user_id: "guest-user",
    assigned_to: "guest-user",
    name: "Kiran Kumar",
    phone: "+919876543005",
    email: "kiran.k@email.com",
    source: "manual",
    budget: 8000000,
    location: "HSR Layout",
    property_type: "plot",
    status: "new",
    notes: "Referred by existing client",
    lead_score: 45,
    lead_priority: "COLD",
    last_interaction_at: toTimestamp(subDays(new Date(), 4)),
    message_count: 1,
    created_at: toTimestamp(subDays(new Date(), 4)),
    updated_at: toTimestamp(subDays(new Date(), 4)),
  },
  {
    id: "lead-6",
    user_id: "guest-user",
    assigned_to: "guest-user",
    name: "Deepa Krishnan",
    phone: "+919876543006",
    source: "whatsapp",
    budget: 5500000,
    location: "Koramangala",
    property_type: "flat",
    status: "closed_won",
    notes: "Purchased 2BHK in Rainbow Residency",
    lead_score: 100,
    lead_priority: "HOT",
    last_interaction_at: toTimestamp(subDays(new Date(), 1)),
    message_count: 15,
    created_at: toTimestamp(subDays(new Date(), 30)),
    updated_at: toTimestamp(subDays(new Date(), 1)),
  },
  {
    id: "lead-7",
    user_id: "guest-user",
    assigned_to: "guest-user",
    name: "Vijay Naidu",
    phone: "+919876543007",
    source: "portal",
    budget: 2000000,
    location: "Yelahanka",
    property_type: "flat",
    status: "closed_lost",
    notes: "Budget constraint, will follow up later",
    lead_score: 20,
    lead_priority: "COLD",
    last_interaction_at: toTimestamp(subDays(new Date(), 15)),
    message_count: 4,
    created_at: toTimestamp(subDays(new Date(), 45)),
    updated_at: toTimestamp(subDays(new Date(), 15)),
  },
  {
    id: "lead-8",
    user_id: "guest-user",
    assigned_to: "guest-user",
    name: "Meera Iyer",
    phone: "+919876543008",
    email: "meera.iyer@email.com",
    source: "website",
    budget: 12000000,
    location: "JP Nagar",
    property_type: "villa",
    status: "visit_scheduled",
    notes: "NRI, visiting next week",
    lead_score: 90,
    lead_priority: "HOT",
    last_interaction_at: toTimestamp(subHours(new Date(), 4)),
    visit_scheduled_at: toTimestamp(addDays(new Date(), 3)),
    message_count: 6,
    created_at: toTimestamp(subDays(new Date(), 7)),
    updated_at: toTimestamp(subHours(new Date(), 4)),
  },
];

export const DUMMY_MESSAGES: Record<string, Message[]> = {
  "lead-1": [
    {
      id: "msg-1-1",
      lead_id: "lead-1",
      direction: "in",
      content:
        "Hi, I saw your property listing for Whitefield. Is it still available?",
      message_type: "text",
      status: "read",
      timestamp: toTimestamp(subDays(new Date(), 5)),
    },
    {
      id: "msg-1-2",
      lead_id: "lead-1",
      direction: "out",
      content:
        "Hello Rahul! Yes, we have several 3BHK options in Whitefield. What's your budget range?",
      message_type: "text",
      status: "delivered",
      timestamp: toTimestamp(subDays(new Date(), 5)),
    },
    {
      id: "msg-1-3",
      lead_id: "lead-1",
      direction: "in",
      content:
        "Around 70-80 lakhs. Looking for gated community with good amenities.",
      message_type: "text",
      status: "read",
      timestamp: toTimestamp(subDays(new Date(), 4)),
    },
    {
      id: "msg-1-4",
      lead_id: "lead-1",
      direction: "out",
      content:
        "Perfect! I have 3 great options for you. Would you like to schedule a site visit this weekend?",
      message_type: "text",
      status: "delivered",
      timestamp: toTimestamp(subDays(new Date(), 4)),
    },
    {
      id: "msg-1-5",
      lead_id: "lead-1",
      direction: "in",
      content: "Yes, Saturday morning works for me.",
      message_type: "text",
      status: "read",
      timestamp: toTimestamp(subHours(new Date(), 2)),
    },
  ],
  "lead-2": [
    {
      id: "msg-2-1",
      lead_id: "lead-2",
      direction: "in",
      content: "Need help finding a flat in Electronic City",
      message_type: "text",
      status: "read",
      timestamp: toTimestamp(subDays(new Date(), 8)),
    },
    {
      id: "msg-2-2",
      lead_id: "lead-2",
      direction: "out",
      content:
        "Hi Priya! Happy to help. What size and budget are you looking at?",
      message_type: "text",
      status: "delivered",
      timestamp: toTimestamp(subDays(new Date(), 8)),
    },
    {
      id: "msg-2-3",
      lead_id: "lead-2",
      direction: "in",
      content:
        "2BHK, around 45 lakhs. First time buying, need loan assistance too.",
      message_type: "text",
      status: "read",
      timestamp: toTimestamp(subDays(new Date(), 7)),
    },
  ],
};

export const DUMMY_TASKS: Task[] = [
  {
    id: "task-1",
    lead_id: "lead-1",
    user_id: "guest-user",
    assigned_to: "guest-user",
    type: "visit",
    title: "Site visit - Whitefield properties",
    description:
      "Show 3 properties: Rainbow Residency, Prestige Lakeside, Brigade Metropolis",
    due_date: toTimestamp(addDays(new Date(), 1)),
    status: "pending",
    created_at: toTimestamp(subDays(new Date(), 1)),
  },
  {
    id: "task-2",
    lead_id: "lead-2",
    user_id: "guest-user",
    assigned_to: "guest-user",
    type: "call",
    title: "Follow up on loan pre-approval",
    description: "Check if loan documents are ready",
    due_date: toTimestamp(addHours(new Date(), 3)),
    status: "pending",
    created_at: toTimestamp(subDays(new Date(), 2)),
  },
  {
    id: "task-3",
    lead_id: "lead-3",
    user_id: "guest-user",
    assigned_to: "guest-user",
    type: "followup",
    title: "Send villa brochures",
    description: "Email brochures for Indiranagar villa projects",
    due_date: toTimestamp(new Date()),
    status: "pending",
    created_at: toTimestamp(subDays(new Date(), 1)),
  },
  {
    id: "task-4",
    lead_id: "lead-8",
    user_id: "guest-user",
    assigned_to: "guest-user",
    type: "visit",
    title: "NRI client site visit",
    description: "JP Nagar villa tour - prepare all documents",
    due_date: toTimestamp(addDays(new Date(), 3)),
    status: "pending",
    created_at: toTimestamp(subDays(new Date(), 2)),
  },
];

export const DUMMY_AUTOMATIONS: Automation[] = [
  {
    id: "auto-1",
    user_id: "guest-user",
    name: "Welcome Message",
    trigger: "lead_created",
    template_name: "welcome_template",
    template_text:
      "Hi {{name}}, thanks for your interest! I'm your dedicated property consultant. How can I help you today?",
    active: true,
    created_at: toTimestamp(subDays(new Date(), 30)),
    updated_at: toTimestamp(subDays(new Date(), 30)),
  },
  {
    id: "auto-2",
    user_id: "guest-user",
    name: "24h Follow-up",
    trigger: "after_hours",
    trigger_value: 24,
    template_name: "followup_24h",
    template_text:
      "Hi {{name}}, just checking in! Did you have any questions about the properties we discussed?",
    active: true,
    created_at: toTimestamp(subDays(new Date(), 30)),
    updated_at: toTimestamp(subDays(new Date(), 30)),
  },
  {
    id: "auto-3",
    user_id: "guest-user",
    name: "3-Day Reminder",
    trigger: "after_days",
    trigger_value: 3,
    template_name: "reminder_3d",
    template_text:
      "Hi {{name}}, we have some new properties that match your requirements. Would you like to schedule a visit?",
    active: true,
    created_at: toTimestamp(subDays(new Date(), 30)),
    updated_at: toTimestamp(subDays(new Date(), 30)),
  },
  {
    id: "auto-4",
    user_id: "guest-user",
    name: "Visit Reminder",
    trigger: "status_changed",
    trigger_status: "visit_scheduled",
    template_name: "visit_reminder",
    template_text:
      "Hi {{name}}, just a reminder about your site visit tomorrow. Looking forward to showing you the properties!",
    active: false,
    created_at: toTimestamp(subDays(new Date(), 15)),
    updated_at: toTimestamp(subDays(new Date(), 15)),
  },
];

export const DUMMY_DASHBOARD_STATS: DashboardStats = {
  total_leads: 8,
  hot_leads: 3,
  warm_leads: 3,
  cold_leads: 2,
  followups_due_today: 3,
  conversion_rate: 12.5,
  leads_by_source: {
    website: 2,
    whatsapp: 2,
    portal: 2,
    facebook: 1,
    manual: 1,
    csv: 0,
    "walk-in": 0,
  },
  leads_by_status: {
    new: 2,
    contacted: 1,
    visit_scheduled: 2,
    negotiation: 1,
    closed_won: 1,
    closed_lost: 1,
  },
  recent_leads: DUMMY_LEADS.slice(0, 5),
  due_tasks: DUMMY_TASKS.filter((t) => t.status === "pending"),
};

export const DUMMY_TEAM_MEMBERS = [
  {
    uid: "guest-user",
    name: "Guest User (You)",
    email: "guest@proplead.com",
    role: "owner" as const,
    lead_count: 8,
  },
  {
    uid: "agent-1",
    name: "Arun Kumar",
    email: "arun@proplead.com",
    role: "agent" as const,
    lead_count: 12,
  },
  {
    uid: "agent-2",
    name: "Sneha Gupta",
    email: "sneha@proplead.com",
    role: "agent" as const,
    lead_count: 8,
  },
];

// Property Listings Dummy Data
import { PropertyListing } from "./types/listing";

export const DUMMY_LISTINGS: PropertyListing[] = [
  {
    id: "listing-1",
    agent_id: "guest-user",
    title: "Luxury 3BHK Apartment in Whitefield",
    description:
      "Spacious 3BHK apartment with premium finishes, modern amenities, and stunning city views. Located in a gated community with 24/7 security.",
    reference_number: "PL-2024-001",
    listing_type: "sale" as const,
    property_category: "apartment" as const,
    status: "active" as const,
    address: "Prestige Lakeside, Whitefield Main Road",
    area: "Whitefield",
    city: "Bangalore",
    country: "India",
    latitude: 12.9698,
    longitude: 77.75,
    bedrooms: 3,
    bathrooms: 3,
    size_sqft: 1850,
    floor_number: 12,
    total_floors: 25,
    parking_spaces: 2,
    furnished: "semi-furnished" as const,
    price: 12500000,
    price_per_sqft: 6757,
    photos: [
      {
        id: "p1",
        url: "/demo/listing1-1.jpg",
        thumbnail_url: "/demo/listing1-1-thumb.jpg",
        order: 1,
        is_primary: true,
      },
      {
        id: "p2",
        url: "/demo/listing1-2.jpg",
        thumbnail_url: "/demo/listing1-2-thumb.jpg",
        order: 2,
        is_primary: false,
      },
    ],
    virtual_tours: [
      {
        id: "vt1",
        type: "360" as const,
        url: "https://example.com/tour/1",
        title: "Living Room Tour",
      },
    ],
    amenities: [
      "swimming_pool",
      "gym",
      "clubhouse",
      "parking",
      "security",
      "power_backup",
    ],
    highlights: ["Corner unit", "Park facing", "Premium flooring"],
    sync_status: [
      {
        platform: "property_finder" as const,
        synced: true,
        last_synced_at: toTimestamp(subHours(new Date(), 2)),
        listing_url: "https://propertyfinder.ae/listing/123",
      },
      {
        platform: "bayut" as const,
        synced: true,
        last_synced_at: toTimestamp(subHours(new Date(), 2)),
        listing_url: "https://bayut.com/listing/123",
      },
      { platform: "dubizzle" as const, synced: false },
      {
        platform: "website" as const,
        synced: true,
        last_synced_at: toTimestamp(subHours(new Date(), 1)),
      },
    ],
    created_at: toTimestamp(subDays(new Date(), 30)),
    updated_at: toTimestamp(subHours(new Date(), 2)),
    published_at: toTimestamp(subDays(new Date(), 28)),
    views: 1250,
    inquiries: 45,
    favorites: 89,
  },
  {
    id: "listing-2",
    agent_id: "guest-user",
    title: "Modern 2BHK in Electronic City",
    description:
      "Brand new 2BHK apartment with contemporary design, close to tech parks. Perfect for working professionals.",
    reference_number: "PL-2024-002",
    listing_type: "rent" as const,
    property_category: "apartment" as const,
    status: "active" as const,
    address: "Brigade Gateway, Electronic City Phase 1",
    area: "Electronic City",
    city: "Bangalore",
    country: "India",
    bedrooms: 2,
    bathrooms: 2,
    size_sqft: 1200,
    floor_number: 8,
    total_floors: 18,
    parking_spaces: 1,
    furnished: "furnished" as const,
    price: 35000,
    rental_period: "monthly" as const,
    photos: [
      {
        id: "p3",
        url: "/demo/listing2-1.jpg",
        thumbnail_url: "/demo/listing2-1-thumb.jpg",
        order: 1,
        is_primary: true,
      },
    ],
    virtual_tours: [],
    amenities: ["gym", "parking", "security", "power_backup", "lift"],
    highlights: ["Ready to move", "Near metro"],
    sync_status: [
      {
        platform: "property_finder" as const,
        synced: true,
        last_synced_at: toTimestamp(subHours(new Date(), 5)),
      },
      {
        platform: "bayut" as const,
        synced: true,
        last_synced_at: toTimestamp(subHours(new Date(), 5)),
      },
      {
        platform: "dubizzle" as const,
        synced: true,
        last_synced_at: toTimestamp(subHours(new Date(), 5)),
      },
      {
        platform: "website" as const,
        synced: true,
        last_synced_at: toTimestamp(subHours(new Date(), 3)),
      },
    ],
    created_at: toTimestamp(subDays(new Date(), 15)),
    updated_at: toTimestamp(subHours(new Date(), 5)),
    published_at: toTimestamp(subDays(new Date(), 14)),
    views: 890,
    inquiries: 32,
    favorites: 56,
  },
  {
    id: "listing-3",
    agent_id: "guest-user",
    title: "Premium Villa in Indiranagar",
    description:
      "Exquisite 4BHK villa with private garden, modern architecture, and premium amenities in prime location.",
    reference_number: "PL-2024-003",
    listing_type: "sale" as const,
    property_category: "villa" as const,
    status: "active" as const,
    address: "100ft Road, Indiranagar",
    area: "Indiranagar",
    city: "Bangalore",
    country: "India",
    bedrooms: 4,
    bathrooms: 4,
    size_sqft: 3500,
    plot_size_sqft: 2400,
    parking_spaces: 3,
    furnished: "unfurnished" as const,
    price: 45000000,
    price_per_sqft: 12857,
    photos: [
      {
        id: "p4",
        url: "/demo/listing3-1.jpg",
        thumbnail_url: "/demo/listing3-1-thumb.jpg",
        order: 1,
        is_primary: true,
      },
    ],
    virtual_tours: [
      {
        id: "vt2",
        type: "video" as const,
        url: "https://youtube.com/watch?v=123",
        title: "Property Walkthrough",
      },
    ],
    amenities: [
      "private_garden",
      "parking",
      "security",
      "power_backup",
      "terrace",
    ],
    highlights: ["Prime location", "Independent villa", "East facing"],
    sync_status: [
      {
        platform: "property_finder" as const,
        synced: true,
        last_synced_at: toTimestamp(subDays(new Date(), 1)),
      },
      {
        platform: "bayut" as const,
        synced: false,
        error: "Authentication expired",
      },
      { platform: "dubizzle" as const, synced: false },
      {
        platform: "website" as const,
        synced: true,
        last_synced_at: toTimestamp(subDays(new Date(), 1)),
      },
    ],
    created_at: toTimestamp(subDays(new Date(), 45)),
    updated_at: toTimestamp(subDays(new Date(), 1)),
    published_at: toTimestamp(subDays(new Date(), 44)),
    views: 2100,
    inquiries: 78,
    favorites: 134,
  },
  {
    id: "listing-4",
    agent_id: "guest-user",
    title: "Studio Apartment near Tech Park",
    description:
      "Compact studio apartment ideal for single professionals. Walking distance to major tech parks.",
    reference_number: "PL-2024-004",
    listing_type: "rent" as const,
    property_category: "studio" as const,
    status: "pending" as const,
    address: "Manyata Tech Park Road",
    area: "Hebbal",
    city: "Bangalore",
    country: "India",
    bedrooms: 0,
    bathrooms: 1,
    size_sqft: 450,
    floor_number: 5,
    total_floors: 12,
    parking_spaces: 1,
    furnished: "furnished" as const,
    price: 18000,
    rental_period: "monthly" as const,
    photos: [],
    virtual_tours: [],
    amenities: ["parking", "security", "lift"],
    highlights: ["Near tech park", "Newly built"],
    sync_status: [
      { platform: "property_finder" as const, synced: false },
      { platform: "bayut" as const, synced: false },
      { platform: "dubizzle" as const, synced: false },
      { platform: "website" as const, synced: false },
    ],
    created_at: toTimestamp(subDays(new Date(), 3)),
    updated_at: toTimestamp(subDays(new Date(), 3)),
    views: 0,
    inquiries: 0,
    favorites: 0,
  },
];

// Lead Ad Integrations Dummy Data
export const DUMMY_INTEGRATIONS = [
  {
    id: "int-1",
    agent_id: "guest-user",
    platform: "facebook" as const,
    status: "active" as const,
    account_id: "123456789",
    account_name: "PropLead Real Estate",
    page_id: "987654321",
    page_name: "PropLead Properties",
    webhook_url: "https://hooks.zapier.com/hooks/catch/123456/abcdef",
    zapier_connected: true,
    auto_assign: true,
    default_status: "new",
    default_source: "facebook",
    notification_email: "leads@proplead.com",
    total_leads_imported: 156,
    last_lead_at: toTimestamp(subHours(new Date(), 3)),
    connected_at: toTimestamp(subDays(new Date(), 60)),
    last_sync_at: toTimestamp(subHours(new Date(), 1)),
  },
  {
    id: "int-2",
    agent_id: "guest-user",
    platform: "instagram" as const,
    status: "active" as const,
    account_id: "123456789",
    account_name: "PropLead Real Estate",
    page_id: "instagram_123",
    page_name: "@proplead_properties",
    webhook_url: "https://hooks.zapier.com/hooks/catch/123456/ghijkl",
    zapier_connected: true,
    auto_assign: true,
    default_status: "new",
    default_source: "portal",
    total_leads_imported: 89,
    last_lead_at: toTimestamp(subHours(new Date(), 8)),
    connected_at: toTimestamp(subDays(new Date(), 45)),
    last_sync_at: toTimestamp(subHours(new Date(), 2)),
  },
  {
    id: "int-3",
    agent_id: "guest-user",
    platform: "google" as const,
    status: "inactive" as const,
    account_id: "google_ads_123",
    account_name: "PropLead Google Ads",
    webhook_url: "",
    zapier_connected: false,
    auto_assign: false,
    default_status: "new",
    default_source: "website",
    total_leads_imported: 0,
    connected_at: toTimestamp(subDays(new Date(), 10)),
  },
];

// Analytics Dummy Data
export const DUMMY_SALES_METRICS = [
  {
    period: "Jan 2024",
    revenue: 2500000,
    deals_closed: 3,
    avg_deal_size: 833333,
    commission: 75000,
  },
  {
    period: "Feb 2024",
    revenue: 3200000,
    deals_closed: 4,
    avg_deal_size: 800000,
    commission: 96000,
  },
  {
    period: "Mar 2024",
    revenue: 4100000,
    deals_closed: 5,
    avg_deal_size: 820000,
    commission: 123000,
  },
  {
    period: "Apr 2024",
    revenue: 3800000,
    deals_closed: 4,
    avg_deal_size: 950000,
    commission: 114000,
  },
  {
    period: "May 2024",
    revenue: 5200000,
    deals_closed: 6,
    avg_deal_size: 866667,
    commission: 156000,
  },
  {
    period: "Jun 2024",
    revenue: 4800000,
    deals_closed: 5,
    avg_deal_size: 960000,
    commission: 144000,
  },
];

export const DUMMY_CONVERSION_METRICS = [
  {
    period: "Jan 2024",
    total_leads: 45,
    qualified_leads: 28,
    converted_leads: 3,
    conversion_rate: 6.7,
    avg_conversion_time_days: 32,
  },
  {
    period: "Feb 2024",
    total_leads: 52,
    qualified_leads: 35,
    converted_leads: 4,
    conversion_rate: 7.7,
    avg_conversion_time_days: 28,
  },
  {
    period: "Mar 2024",
    total_leads: 68,
    qualified_leads: 42,
    converted_leads: 5,
    conversion_rate: 7.4,
    avg_conversion_time_days: 25,
  },
  {
    period: "Apr 2024",
    total_leads: 58,
    qualified_leads: 38,
    converted_leads: 4,
    conversion_rate: 6.9,
    avg_conversion_time_days: 30,
  },
  {
    period: "May 2024",
    total_leads: 75,
    qualified_leads: 48,
    converted_leads: 6,
    conversion_rate: 8.0,
    avg_conversion_time_days: 22,
  },
  {
    period: "Jun 2024",
    total_leads: 82,
    qualified_leads: 55,
    converted_leads: 5,
    conversion_rate: 6.1,
    avg_conversion_time_days: 27,
  },
];

export const DUMMY_REVENUE_PROJECTIONS = [
  {
    period: "Jul 2024",
    projected_revenue: 5500000,
    pipeline_value: 18000000,
    confidence: 0.72,
  },
  {
    period: "Aug 2024",
    projected_revenue: 6200000,
    pipeline_value: 22000000,
    confidence: 0.65,
  },
  {
    period: "Sep 2024",
    projected_revenue: 5800000,
    pipeline_value: 25000000,
    confidence: 0.58,
  },
  {
    period: "Oct 2024",
    projected_revenue: 7000000,
    pipeline_value: 28000000,
    confidence: 0.52,
  },
  {
    period: "Nov 2024",
    projected_revenue: 6500000,
    pipeline_value: 30000000,
    confidence: 0.45,
  },
  {
    period: "Dec 2024",
    projected_revenue: 8000000,
    pipeline_value: 35000000,
    confidence: 0.4,
  },
];

export const DUMMY_SOURCE_PERFORMANCE = [
  {
    source: "Website",
    leads: 120,
    conversions: 12,
    conversion_rate: 10.0,
    revenue: 8500000,
    cost_per_lead: 250,
    roi: 340,
  },
  {
    source: "Facebook Ads",
    leads: 156,
    conversions: 8,
    conversion_rate: 5.1,
    revenue: 5200000,
    cost_per_lead: 180,
    roi: 185,
  },
  {
    source: "Instagram Ads",
    leads: 89,
    conversions: 5,
    conversion_rate: 5.6,
    revenue: 3800000,
    cost_per_lead: 220,
    roi: 192,
  },
  {
    source: "Property Portals",
    leads: 85,
    conversions: 7,
    conversion_rate: 8.2,
    revenue: 6100000,
    cost_per_lead: 350,
    roi: 204,
  },
  {
    source: "WhatsApp",
    leads: 45,
    conversions: 6,
    conversion_rate: 13.3,
    revenue: 4500000,
    cost_per_lead: 0,
    roi: 999,
  },
  {
    source: "Referrals",
    leads: 32,
    conversions: 8,
    conversion_rate: 25.0,
    revenue: 7200000,
    cost_per_lead: 0,
    roi: 999,
  },
];

export const DUMMY_AGENT_PERFORMANCE = [
  {
    agent_id: "guest-user",
    agent_name: "Guest User",
    leads_handled: 85,
    deals_closed: 12,
    revenue: 9500000,
    conversion_rate: 14.1,
    avg_response_time_mins: 15,
    customer_rating: 4.8,
  },
  {
    agent_id: "agent-1",
    agent_name: "Arun Kumar",
    leads_handled: 120,
    deals_closed: 18,
    revenue: 12500000,
    conversion_rate: 15.0,
    avg_response_time_mins: 12,
    customer_rating: 4.9,
  },
  {
    agent_id: "agent-2",
    agent_name: "Sneha Gupta",
    leads_handled: 95,
    deals_closed: 14,
    revenue: 10200000,
    conversion_rate: 14.7,
    avg_response_time_mins: 18,
    customer_rating: 4.7,
  },
];

// Lead Ad Campaigns Dummy Data
export const DUMMY_AD_CAMPAIGNS = [
  {
    id: "camp-1",
    integration_id: "int-1",
    platform: "facebook" as const,
    campaign_id: "fb_camp_123",
    campaign_name: "Whitefield Apartments - Q1 2024",
    ad_set_name: "3BHK Buyers 25-45",
    ad_name: "Premium Living Ad",
    status: "active" as const,
    leads_count: 78,
    spend: 45000,
    cost_per_lead: 577,
    start_date: toTimestamp(subDays(new Date(), 45)),
  },
  {
    id: "camp-2",
    integration_id: "int-1",
    platform: "facebook" as const,
    campaign_id: "fb_camp_456",
    campaign_name: "Electronic City Rentals",
    ad_set_name: "IT Professionals",
    ad_name: "Tech Hub Living",
    status: "active" as const,
    leads_count: 45,
    spend: 28000,
    cost_per_lead: 622,
    start_date: toTimestamp(subDays(new Date(), 30)),
  },
  {
    id: "camp-3",
    integration_id: "int-2",
    platform: "instagram" as const,
    campaign_id: "ig_camp_789",
    campaign_name: "Luxury Villas Showcase",
    ad_set_name: "High Net Worth",
    ad_name: "Dream Villa Carousel",
    status: "active" as const,
    leads_count: 32,
    spend: 35000,
    cost_per_lead: 1094,
    start_date: toTimestamp(subDays(new Date(), 20)),
  },
  {
    id: "camp-4",
    integration_id: "int-1",
    platform: "facebook" as const,
    campaign_id: "fb_camp_101",
    campaign_name: "First Home Buyers",
    ad_set_name: "Young Professionals",
    status: "completed" as const,
    leads_count: 33,
    spend: 22000,
    cost_per_lead: 667,
    start_date: toTimestamp(subDays(new Date(), 90)),
    end_date: toTimestamp(subDays(new Date(), 60)),
  },
];
