// Dummy data for Guest Mode demonstration

import { Timestamp } from "firebase/firestore";
import { Lead, Message, Task, Automation, DashboardStats } from "./types";
import { subDays, subHours, addDays, addHours } from "date-fns";

// Helper to create Timestamp from Date
const toTimestamp = (date: Date) => Timestamp.fromDate(date);

export const DUMMY_LEADS: Lead[] = [
  {
    id: "lead-1",
    user_id: "guest-user",
    assigned_to: "guest-user",
    name: "Rahul Sharma",
    phone: "+919876543001",
    email: "rahul.sharma@email.com",
    source: "website",
    budget: 7500000,
    location: "Whitefield, Bangalore",
    property_type: "flat",
    status: "visit_scheduled",
    notes: "Looking for 3BHK, interested in gated community",
    tags: ["premium"],
    lead_score: 85,
    lead_priority: "HOT",
    last_interaction_at: toTimestamp(subHours(new Date(), 2)),
    visit_scheduled_at: toTimestamp(addDays(new Date(), 1)),
    message_count: 8,
    created_at: toTimestamp(subDays(new Date(), 5)),
    updated_at: toTimestamp(subHours(new Date(), 2)),
  },
  {
    id: "lead-2",
    user_id: "guest-user",
    assigned_to: "guest-user",
    name: "Priya Menon",
    phone: "+919876543002",
    email: "priya.m@email.com",
    source: "whatsapp",
    budget: 4500000,
    location: "Electronic City",
    property_type: "flat",
    status: "negotiation",
    notes: "First-time buyer, needs loan assistance",
    lead_score: 72,
    lead_priority: "WARM",
    last_interaction_at: toTimestamp(subHours(new Date(), 6)),
    message_count: 5,
    created_at: toTimestamp(subDays(new Date(), 8)),
    updated_at: toTimestamp(subHours(new Date(), 6)),
  },
  {
    id: "lead-3",
    user_id: "guest-user",
    assigned_to: "guest-user",
    name: "Amit Patel",
    phone: "+919876543003",
    email: "amit.patel@email.com",
    source: "portal",
    budget: 15000000,
    location: "Indiranagar",
    property_type: "villa",
    status: "new",
    notes: "Investment purpose, looking for ready-to-move",
    lead_score: 65,
    lead_priority: "WARM",
    last_interaction_at: toTimestamp(subDays(new Date(), 1)),
    message_count: 2,
    created_at: toTimestamp(subDays(new Date(), 2)),
    updated_at: toTimestamp(subDays(new Date(), 1)),
  },
  {
    id: "lead-4",
    user_id: "guest-user",
    assigned_to: "guest-user",
    name: "Sunita Reddy",
    phone: "+919876543004",
    source: "facebook",
    budget: 3500000,
    location: "Marathahalli",
    property_type: "flat",
    status: "contacted",
    lead_score: 55,
    lead_priority: "WARM",
    last_interaction_at: toTimestamp(subDays(new Date(), 2)),
    message_count: 3,
    created_at: toTimestamp(subDays(new Date(), 10)),
    updated_at: toTimestamp(subDays(new Date(), 2)),
  },
  {
    id: "lead-5",
    user_id: "guest-user",
    assigned_to: "guest-user",
    name: "Kiran Kumar",
    phone: "+919876543005",
    email: "kiran.k@email.com",
    source: "manual",
    budget: 8000000,
    location: "HSR Layout",
    property_type: "plot",
    status: "new",
    notes: "Referred by existing client",
    lead_score: 45,
    lead_priority: "COLD",
    last_interaction_at: toTimestamp(subDays(new Date(), 4)),
    message_count: 1,
    created_at: toTimestamp(subDays(new Date(), 4)),
    updated_at: toTimestamp(subDays(new Date(), 4)),
  },
  {
    id: "lead-6",
    user_id: "guest-user",
    assigned_to: "guest-user",
    name: "Deepa Krishnan",
    phone: "+919876543006",
    source: "whatsapp",
    budget: 5500000,
    location: "Koramangala",
    property_type: "flat",
    status: "closed_won",
    notes: "Purchased 2BHK in Rainbow Residency",
    lead_score: 100,
    lead_priority: "HOT",
    last_interaction_at: toTimestamp(subDays(new Date(), 1)),
    message_count: 15,
    created_at: toTimestamp(subDays(new Date(), 30)),
    updated_at: toTimestamp(subDays(new Date(), 1)),
  },
  {
    id: "lead-7",
    user_id: "guest-user",
    assigned_to: "guest-user",
    name: "Vijay Naidu",
    phone: "+919876543007",
    source: "portal",
    budget: 2000000,
    location: "Yelahanka",
    property_type: "flat",
    status: "closed_lost",
    notes: "Budget constraint, will follow up later",
    lead_score: 20,
    lead_priority: "COLD",
    last_interaction_at: toTimestamp(subDays(new Date(), 15)),
    message_count: 4,
    created_at: toTimestamp(subDays(new Date(), 45)),
    updated_at: toTimestamp(subDays(new Date(), 15)),
  },
  {
    id: "lead-8",
    user_id: "guest-user",
    assigned_to: "guest-user",
    name: "Meera Iyer",
    phone: "+919876543008",
    email: "meera.iyer@email.com",
    source: "website",
    budget: 12000000,
    location: "JP Nagar",
    property_type: "villa",
    status: "visit_scheduled",
    notes: "NRI, visiting next week",
    lead_score: 90,
    lead_priority: "HOT",
    last_interaction_at: toTimestamp(subHours(new Date(), 4)),
    visit_scheduled_at: toTimestamp(addDays(new Date(), 3)),
    message_count: 6,
    created_at: toTimestamp(subDays(new Date(), 7)),
    updated_at: toTimestamp(subHours(new Date(), 4)),
  },
];

export const DUMMY_MESSAGES: Record<string, Message[]> = {
  "lead-1": [
    {
      id: "msg-1-1",
      lead_id: "lead-1",
      direction: "in",
      content:
        "Hi, I saw your property listing for Whitefield. Is it still available?",
      message_type: "text",
      status: "read",
      timestamp: toTimestamp(subDays(new Date(), 5)),
    },
    {
      id: "msg-1-2",
      lead_id: "lead-1",
      direction: "out",
      content:
        "Hello Rahul! Yes, we have several 3BHK options in Whitefield. What's your budget range?",
      message_type: "text",
      status: "delivered",
      timestamp: toTimestamp(subDays(new Date(), 5)),
    },
    {
      id: "msg-1-3",
      lead_id: "lead-1",
      direction: "in",
      content:
        "Around 70-80 lakhs. Looking for gated community with good amenities.",
      message_type: "text",
      status: "read",
      timestamp: toTimestamp(subDays(new Date(), 4)),
    },
    {
      id: "msg-1-4",
      lead_id: "lead-1",
      direction: "out",
      content:
        "Perfect! I have 3 great options for you. Would you like to schedule a site visit this weekend?",
      message_type: "text",
      status: "delivered",
      timestamp: toTimestamp(subDays(new Date(), 4)),
    },
    {
      id: "msg-1-5",
      lead_id: "lead-1",
      direction: "in",
      content: "Yes, Saturday morning works for me.",
      message_type: "text",
      status: "read",
      timestamp: toTimestamp(subHours(new Date(), 2)),
    },
  ],
  "lead-2": [
    {
      id: "msg-2-1",
      lead_id: "lead-2",
      direction: "in",
      content: "Need help finding a flat in Electronic City",
      message_type: "text",
      status: "read",
      timestamp: toTimestamp(subDays(new Date(), 8)),
    },
    {
      id: "msg-2-2",
      lead_id: "lead-2",
      direction: "out",
      content:
        "Hi Priya! Happy to help. What size and budget are you looking at?",
      message_type: "text",
      status: "delivered",
      timestamp: toTimestamp(subDays(new Date(), 8)),
    },
    {
      id: "msg-2-3",
      lead_id: "lead-2",
      direction: "in",
      content:
        "2BHK, around 45 lakhs. First time buying, need loan assistance too.",
      message_type: "text",
      status: "read",
      timestamp: toTimestamp(subDays(new Date(), 7)),
    },
  ],
};

export const DUMMY_TASKS: Task[] = [
  {
    id: "task-1",
    lead_id: "lead-1",
    user_id: "guest-user",
    assigned_to: "guest-user",
    type: "visit",
    title: "Site visit - Whitefield properties",
    description:
      "Show 3 properties: Rainbow Residency, Prestige Lakeside, Brigade Metropolis",
    due_date: toTimestamp(addDays(new Date(), 1)),
    status: "pending",
    created_at: toTimestamp(subDays(new Date(), 1)),
  },
  {
    id: "task-2",
    lead_id: "lead-2",
    user_id: "guest-user",
    assigned_to: "guest-user",
    type: "call",
    title: "Follow up on loan pre-approval",
    description: "Check if loan documents are ready",
    due_date: toTimestamp(addHours(new Date(), 3)),
    status: "pending",
    created_at: toTimestamp(subDays(new Date(), 2)),
  },
  {
    id: "task-3",
    lead_id: "lead-3",
    user_id: "guest-user",
    assigned_to: "guest-user",
    type: "followup",
    title: "Send villa brochures",
    description: "Email brochures for Indiranagar villa projects",
    due_date: toTimestamp(new Date()),
    status: "pending",
    created_at: toTimestamp(subDays(new Date(), 1)),
  },
  {
    id: "task-4",
    lead_id: "lead-8",
    user_id: "guest-user",
    assigned_to: "guest-user",
    type: "visit",
    title: "NRI client site visit",
    description: "JP Nagar villa tour - prepare all documents",
    due_date: toTimestamp(addDays(new Date(), 3)),
    status: "pending",
    created_at: toTimestamp(subDays(new Date(), 2)),
  },
];

export const DUMMY_AUTOMATIONS: Automation[] = [
  {
    id: "auto-1",
    user_id: "guest-user",
    name: "Welcome Message",
    trigger: "lead_created",
    template_name: "welcome_template",
    template_text:
      "Hi {{name}}, thanks for your interest! I'm your dedicated property consultant. How can I help you today?",
    active: true,
    created_at: toTimestamp(subDays(new Date(), 30)),
    updated_at: toTimestamp(subDays(new Date(), 30)),
  },
  {
    id: "auto-2",
    user_id: "guest-user",
    name: "24h Follow-up",
    trigger: "after_hours",
    trigger_value: 24,
    template_name: "followup_24h",
    template_text:
      "Hi {{name}}, just checking in! Did you have any questions about the properties we discussed?",
    active: true,
    created_at: toTimestamp(subDays(new Date(), 30)),
    updated_at: toTimestamp(subDays(new Date(), 30)),
  },
  {
    id: "auto-3",
    user_id: "guest-user",
    name: "3-Day Reminder",
    trigger: "after_days",
    trigger_value: 3,
    template_name: "reminder_3d",
    template_text:
      "Hi {{name}}, we have some new properties that match your requirements. Would you like to schedule a visit?",
    active: true,
    created_at: toTimestamp(subDays(new Date(), 30)),
    updated_at: toTimestamp(subDays(new Date(), 30)),
  },
  {
    id: "auto-4",
    user_id: "guest-user",
    name: "Visit Reminder",
    trigger: "status_changed",
    trigger_status: "visit_scheduled",
    template_name: "visit_reminder",
    template_text:
      "Hi {{name}}, just a reminder about your site visit tomorrow. Looking forward to showing you the properties!",
    active: false,
    created_at: toTimestamp(subDays(new Date(), 15)),
    updated_at: toTimestamp(subDays(new Date(), 15)),
  },
];

export const DUMMY_DASHBOARD_STATS: DashboardStats = {
  total_leads: 8,
  hot_leads: 3,
  warm_leads: 3,
  cold_leads: 2,
  followups_due_today: 3,
  conversion_rate: 12.5,
  leads_by_source: {
    website: 2,
    whatsapp: 2,
    portal: 2,
    facebook: 1,
    manual: 1,
    csv: 0,
    "walk-in": 0,
  },
  leads_by_status: {
    new: 2,
    contacted: 1,
    visit_scheduled: 2,
    negotiation: 1,
    closed_won: 1,
    closed_lost: 1,
  },
  recent_leads: DUMMY_LEADS.slice(0, 5),
  due_tasks: DUMMY_TASKS.filter((t) => t.status === "pending"),
};

export const DUMMY_TEAM_MEMBERS = [
  {
    uid: "guest-user",
    name: "Guest User (You)",
    email: "guest@proplead.com",
    role: "owner" as const,
    lead_count: 8,
  },
  {
    uid: "agent-1",
    name: "Arun Kumar",
    email: "arun@proplead.com",
    role: "agent" as const,
    lead_count: 12,
  },
  {
    uid: "agent-2",
    name: "Sneha Gupta",
    email: "sneha@proplead.com",
    role: "agent" as const,
    lead_count: 8,
  },
];
